name: ImaGenie - Pytorch Nvidia Stylegan
channels:
  - defaults
dependencies:
  - ca-certificates==2023.01
  - certifi==2022.12
  - charset-normalizer==3.1.0
  - openssl=1.1.1t
  - pip=22.3.1
  - python==3.7.16
  - setuptools==65.6.3
  - sqlite==3.41.2
  - vc==14.2
  - vs2015_runtime==14.27.29
  - wheel==0.38.4
  - wincertstore==0.2
  - pip:
    - click==8.1.3
    - colorama==0.4.6
    - importlib-metadata==6.6.0
    - numpy==1.21.6
    - pillow==9.5.0
    - pyqt5==5.15.9
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.12.1
    - requests==2.29.0
    - scipy==1.7.3
    - torch==1.7.1+cu1
    - torchaudio==0.7.2
    - torchvision==0.8.2+cu1
    - tqdm==4.65.0
    - typing_extensions==4.5.0
    - urlib3==1.26.15
    - zipp==3.15.0